/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package distributed.systems;

import distributed.systems.cluster.Orchestrator;
import distributed.systems.election.LeaderElection;
import distributed.systems.election.WatcherExample;
import distributed.systems.networking.WebServer;
import org.apache.zookeeper.KeeperException;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, InterruptedException, KeeperException {
        leaderElection();
//        watcherExample();
//        clusterManagement(args);
//        webserver(args);
    }

    private static void webserver(String[] args) {
        WebServer server = new WebServer(8080);
        server.startServer();
    }

    public static void clusterManagement(String[] args) throws IOException, InterruptedException, KeeperException {
        Orchestrator orchestrator = new Orchestrator(args);
    }

    private static void leaderElection() throws IOException, InterruptedException, KeeperException {
        LeaderElection le = new LeaderElection();
        le.connectToZookeeper();
        le.volunteerForLeadership();
        le.reelectLeader();
        le.run();
        le.close();
        System.out.println("Disconnected from zookeer!");
    }

    public static void watcherExample() throws IOException, InterruptedException {
        WatcherExample we = new WatcherExample();
        we.connectToZookeeper();
        we.run();
        we.close();
    }
}
